
#define PIN_LCD_MOSI 19
#define PIN_LCD_SCK 18
#define PIN_LCD_CS 24
#define PIN_LCD_DC 22
#define PIN_LCD_RST 21
#define PIN_LCD_BACKLIGHT 25

#define PIN_BUTTON_UP 28
#define PIN_BUTTON_DOWN 23
#define PIN_BUTTON_LEFT 16
#define PIN_BUTTON_RIGHT 20
#define PIN_BUTTON_CENTER 17

#define PIN_I2C_SDA 2
#define PIN_I2C_SCL 3
#define I2C_INST i2c1

#define PIN_ENABLE_12V 7
#define PIN_ENABLE_24V 15
#define PIN_ENABLE_LAMP 14
#define PIN_STATUS_LAMP 12
#define PIN_PWM_LAMP 13

#define PIN_VSENSE_VBUS 26
#define PIN_VSENSE_12V 27
#define PIN_VSENSE_24V 29

#define PIN_FAN_PWM 10

#define PIN_MMWAVE_TX 0
#define PIN_MMWAVE_RX 1
#define UART_INST_MMWAVE uart0

#define PIN_RADIO_RX 4
#define PIN_RADIO_TX 5
#define PIN_RADIO_ENABLE 6
#define UART_INST_RADIO uart1
